// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RoriaSharp.Api.Admin.User.Item.Tunnels
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TunnelsGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::RoriaSharp.Api.Admin.User.Item.Tunnels.TunnelsGetResponse_data_items>? Items { get; set; }
#nullable restore
#else
        public List<global::RoriaSharp.Api.Admin.User.Item.Tunnels.TunnelsGetResponse_data_items> Items { get; set; }
#endif
        /// <summary>The limit property</summary>
        public int? Limit { get; set; }
        /// <summary>The page property</summary>
        public int? Page { get; set; }
        /// <summary>The total property</summary>
        public int? Total { get; set; }
        /// <summary>The user_id property</summary>
        public int? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.Admin.User.Item.Tunnels.TunnelsGetResponse_data"/> and sets the default values.
        /// </summary>
        public TunnelsGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RoriaSharp.Api.Admin.User.Item.Tunnels.TunnelsGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RoriaSharp.Api.Admin.User.Item.Tunnels.TunnelsGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RoriaSharp.Api.Admin.User.Item.Tunnels.TunnelsGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::RoriaSharp.Api.Admin.User.Item.Tunnels.TunnelsGetResponse_data_items>(global::RoriaSharp.Api.Admin.User.Item.Tunnels.TunnelsGetResponse_data_items.CreateFromDiscriminatorValue)?.AsList(); } },
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
                { "user_id", n => { UserId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::RoriaSharp.Api.Admin.User.Item.Tunnels.TunnelsGetResponse_data_items>("items", Items);
            writer.WriteIntValue("limit", Limit);
            writer.WriteIntValue("page", Page);
            writer.WriteIntValue("total", Total);
            writer.WriteIntValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
