// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RoriaSharp.Api.User.Checkin;
using RoriaSharp.Api.User.Domain;
using RoriaSharp.Api.User.Frpc;
using RoriaSharp.Api.User.Info;
using RoriaSharp.Api.User.Kyc;
using RoriaSharp.Api.User.Login;
using RoriaSharp.Api.User.Logout;
using RoriaSharp.Api.User.Nodes;
using RoriaSharp.Api.User.Oauth;
using RoriaSharp.Api.User.Register;
using RoriaSharp.Api.User.ResetPassword;
using RoriaSharp.Api.User.SendEmail;
using RoriaSharp.Api.User.Traffic;
using RoriaSharp.Api.User.Tunnel;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RoriaSharp.Api.User
{
    /// <summary>
    /// Builds and executes requests for operations under \user
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The checkin property</summary>
        public global::RoriaSharp.Api.User.Checkin.CheckinRequestBuilder Checkin
        {
            get => new global::RoriaSharp.Api.User.Checkin.CheckinRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The domain property</summary>
        public global::RoriaSharp.Api.User.Domain.DomainRequestBuilder Domain
        {
            get => new global::RoriaSharp.Api.User.Domain.DomainRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The frpc property</summary>
        public global::RoriaSharp.Api.User.Frpc.FrpcRequestBuilder Frpc
        {
            get => new global::RoriaSharp.Api.User.Frpc.FrpcRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The info property</summary>
        public global::RoriaSharp.Api.User.Info.InfoRequestBuilder Info
        {
            get => new global::RoriaSharp.Api.User.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The kyc property</summary>
        public global::RoriaSharp.Api.User.Kyc.KycRequestBuilder Kyc
        {
            get => new global::RoriaSharp.Api.User.Kyc.KycRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::RoriaSharp.Api.User.Login.LoginRequestBuilder Login
        {
            get => new global::RoriaSharp.Api.User.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::RoriaSharp.Api.User.Logout.LogoutRequestBuilder Logout
        {
            get => new global::RoriaSharp.Api.User.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The nodes property</summary>
        public global::RoriaSharp.Api.User.Nodes.NodesRequestBuilder Nodes
        {
            get => new global::RoriaSharp.Api.User.Nodes.NodesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::RoriaSharp.Api.User.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::RoriaSharp.Api.User.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::RoriaSharp.Api.User.Register.RegisterRequestBuilder Register
        {
            get => new global::RoriaSharp.Api.User.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resetPassword property</summary>
        public global::RoriaSharp.Api.User.ResetPassword.ResetPasswordRequestBuilder ResetPassword
        {
            get => new global::RoriaSharp.Api.User.ResetPassword.ResetPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendEmail property</summary>
        public global::RoriaSharp.Api.User.SendEmail.SendEmailRequestBuilder SendEmail
        {
            get => new global::RoriaSharp.Api.User.SendEmail.SendEmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The traffic property</summary>
        public global::RoriaSharp.Api.User.Traffic.TrafficRequestBuilder Traffic
        {
            get => new global::RoriaSharp.Api.User.Traffic.TrafficRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tunnel property</summary>
        public global::RoriaSharp.Api.User.Tunnel.TunnelRequestBuilder Tunnel
        {
            get => new global::RoriaSharp.Api.User.Tunnel.TunnelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
