// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RoriaSharp.Api.User.Frpc.Config;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RoriaSharp.Api.User.Frpc
{
    /// <summary>
    /// Builds and executes requests for operations under \user\frpc
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FrpcRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The config property</summary>
        public global::RoriaSharp.Api.User.Frpc.Config.ConfigRequestBuilder Config
        {
            get => new global::RoriaSharp.Api.User.Frpc.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.Frpc.FrpcRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FrpcRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/frpc", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.Frpc.FrpcRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FrpcRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/frpc", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
