// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RoriaSharp.Api.User.Traffic.Tunnels
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TunnelsGetResponse_data_tunnels : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The max_connections property</summary>
        public int? MaxConnections { get; set; }
        /// <summary>The node_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeId { get; set; }
#nullable restore
#else
        public string NodeId { get; set; }
#endif
        /// <summary>The remark property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remark { get; set; }
#nullable restore
#else
        public string Remark { get; set; }
#endif
        /// <summary>The total_in property</summary>
        public int? TotalIn { get; set; }
        /// <summary>The total_out property</summary>
        public int? TotalOut { get; set; }
        /// <summary>The total_traffic property</summary>
        public int? TotalTraffic { get; set; }
        /// <summary>The tunnel_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TunnelName { get; set; }
#nullable restore
#else
        public string TunnelName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.Traffic.Tunnels.TunnelsGetResponse_data_tunnels"/> and sets the default values.
        /// </summary>
        public TunnelsGetResponse_data_tunnels()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RoriaSharp.Api.User.Traffic.Tunnels.TunnelsGetResponse_data_tunnels"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RoriaSharp.Api.User.Traffic.Tunnels.TunnelsGetResponse_data_tunnels CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RoriaSharp.Api.User.Traffic.Tunnels.TunnelsGetResponse_data_tunnels();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "max_connections", n => { MaxConnections = n.GetIntValue(); } },
                { "node_id", n => { NodeId = n.GetStringValue(); } },
                { "remark", n => { Remark = n.GetStringValue(); } },
                { "total_in", n => { TotalIn = n.GetIntValue(); } },
                { "total_out", n => { TotalOut = n.GetIntValue(); } },
                { "total_traffic", n => { TotalTraffic = n.GetIntValue(); } },
                { "tunnel_name", n => { TunnelName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("max_connections", MaxConnections);
            writer.WriteStringValue("node_id", NodeId);
            writer.WriteStringValue("remark", Remark);
            writer.WriteIntValue("total_in", TotalIn);
            writer.WriteIntValue("total_out", TotalOut);
            writer.WriteIntValue("total_traffic", TotalTraffic);
            writer.WriteStringValue("tunnel_name", TunnelName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
