// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RoriaSharp.Api.Admin.Stats
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StatsGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The online_tunnel_count property</summary>
        public int? OnlineTunnelCount { get; set; }
        /// <summary>The total_traffic_used property</summary>
        public int? TotalTrafficUsed { get; set; }
        /// <summary>The total_tunnel_count property</summary>
        public int? TotalTunnelCount { get; set; }
        /// <summary>The user_count property</summary>
        public int? UserCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.Admin.Stats.StatsGetResponse_data"/> and sets the default values.
        /// </summary>
        public StatsGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RoriaSharp.Api.Admin.Stats.StatsGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RoriaSharp.Api.Admin.Stats.StatsGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RoriaSharp.Api.Admin.Stats.StatsGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "online_tunnel_count", n => { OnlineTunnelCount = n.GetIntValue(); } },
                { "total_traffic_used", n => { TotalTrafficUsed = n.GetIntValue(); } },
                { "total_tunnel_count", n => { TotalTunnelCount = n.GetIntValue(); } },
                { "user_count", n => { UserCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("online_tunnel_count", OnlineTunnelCount);
            writer.WriteIntValue("total_traffic_used", TotalTrafficUsed);
            writer.WriteIntValue("total_tunnel_count", TotalTunnelCount);
            writer.WriteIntValue("user_count", UserCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
