// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RoriaSharp.Api.User.Info
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InfoGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The avatar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Avatar { get; set; }
#nullable restore
#else
        public string Avatar { get; set; }
#endif
        /// <summary>The bandwidth_limit property</summary>
        public int? BandwidthLimit { get; set; }
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The has_kyc property</summary>
        public bool? HasKyc { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The is_baned property</summary>
        public bool? IsBaned { get; set; }
        /// <summary>The kyc_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KycStatus { get; set; }
#nullable restore
#else
        public string KycStatus { get; set; }
#endif
        /// <summary>The max_tunnel_count property</summary>
        public int? MaxTunnelCount { get; set; }
        /// <summary>The role property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif
        /// <summary>The today_checked property</summary>
        public bool? TodayChecked { get; set; }
        /// <summary>The traffic_limit property</summary>
        public long? TrafficLimit { get; set; }
        /// <summary>The traffic_used property</summary>
        public long? TrafficUsed { get; set; }
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.Info.InfoGetResponse_data"/> and sets the default values.
        /// </summary>
        public InfoGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RoriaSharp.Api.User.Info.InfoGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RoriaSharp.Api.User.Info.InfoGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RoriaSharp.Api.User.Info.InfoGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avatar", n => { Avatar = n.GetStringValue(); } },
                { "bandwidth_limit", n => { BandwidthLimit = n.GetIntValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "has_kyc", n => { HasKyc = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_baned", n => { IsBaned = n.GetBoolValue(); } },
                { "kyc_status", n => { KycStatus = n.GetStringValue(); } },
                { "max_tunnel_count", n => { MaxTunnelCount = n.GetIntValue(); } },
                { "role", n => { Role = n.GetStringValue(); } },
                { "today_checked", n => { TodayChecked = n.GetBoolValue(); } },
                { "traffic_limit", n => { TrafficLimit = n.GetLongValue(); } },
                { "traffic_used", n => { TrafficUsed = n.GetLongValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("avatar", Avatar);
            writer.WriteIntValue("bandwidth_limit", BandwidthLimit);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("email", Email);
            writer.WriteBoolValue("has_kyc", HasKyc);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_baned", IsBaned);
            writer.WriteStringValue("kyc_status", KycStatus);
            writer.WriteIntValue("max_tunnel_count", MaxTunnelCount);
            writer.WriteStringValue("role", Role);
            writer.WriteBoolValue("today_checked", TodayChecked);
            writer.WriteLongValue("traffic_limit", TrafficLimit);
            writer.WriteLongValue("traffic_used", TrafficUsed);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
