// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RoriaSharp.Api.User.Kyc.Init;
using RoriaSharp.Api.User.Kyc.Query;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RoriaSharp.Api.User.Kyc
{
    /// <summary>
    /// Builds and executes requests for operations under \user\kyc
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KycRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The init property</summary>
        public global::RoriaSharp.Api.User.Kyc.Init.InitRequestBuilder Init
        {
            get => new global::RoriaSharp.Api.User.Kyc.Init.InitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The query property</summary>
        public global::RoriaSharp.Api.User.Kyc.Query.QueryRequestBuilder Query
        {
            get => new global::RoriaSharp.Api.User.Kyc.Query.QueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.Kyc.KycRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KycRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/kyc", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.Kyc.KycRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KycRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/kyc", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
