// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RoriaSharp.Api.User.Tunnel.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithTunnel_nameGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The auto_tls property</summary>
        public bool? AutoTls { get; set; }
        /// <summary>The bandwidth_limit property</summary>
        public int? BandwidthLimit { get; set; }
        /// <summary>The client_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientVersion { get; set; }
#nullable restore
#else
        public string ClientVersion { get; set; }
#endif
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The custom_domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomDomain { get; set; }
#nullable restore
#else
        public string CustomDomain { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The local_ip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocalIp { get; set; }
#nullable restore
#else
        public string LocalIp { get; set; }
#endif
        /// <summary>The local_port property</summary>
        public int? LocalPort { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The node_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeAddress { get; set; }
#nullable restore
#else
        public string NodeAddress { get; set; }
#endif
        /// <summary>The node_id property</summary>
        public int? NodeId { get; set; }
        /// <summary>The node_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeName { get; set; }
#nullable restore
#else
        public string NodeName { get; set; }
#endif
        /// <summary>The remark property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remark { get; set; }
#nullable restore
#else
        public string Remark { get; set; }
#endif
        /// <summary>The remote_port property</summary>
        public int? RemotePort { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The tunnel_token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TunnelToken { get; set; }
#nullable restore
#else
        public string TunnelToken { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.Tunnel.Item.WithTunnel_nameGetResponse_data"/> and sets the default values.
        /// </summary>
        public WithTunnel_nameGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RoriaSharp.Api.User.Tunnel.Item.WithTunnel_nameGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RoriaSharp.Api.User.Tunnel.Item.WithTunnel_nameGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RoriaSharp.Api.User.Tunnel.Item.WithTunnel_nameGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auto_tls", n => { AutoTls = n.GetBoolValue(); } },
                { "bandwidth_limit", n => { BandwidthLimit = n.GetIntValue(); } },
                { "client_version", n => { ClientVersion = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "custom_domain", n => { CustomDomain = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "local_ip", n => { LocalIp = n.GetStringValue(); } },
                { "local_port", n => { LocalPort = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "node_address", n => { NodeAddress = n.GetStringValue(); } },
                { "node_id", n => { NodeId = n.GetIntValue(); } },
                { "node_name", n => { NodeName = n.GetStringValue(); } },
                { "remark", n => { Remark = n.GetStringValue(); } },
                { "remote_port", n => { RemotePort = n.GetIntValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "tunnel_token", n => { TunnelToken = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("auto_tls", AutoTls);
            writer.WriteIntValue("bandwidth_limit", BandwidthLimit);
            writer.WriteStringValue("client_version", ClientVersion);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("custom_domain", CustomDomain);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("local_ip", LocalIp);
            writer.WriteIntValue("local_port", LocalPort);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("node_address", NodeAddress);
            writer.WriteIntValue("node_id", NodeId);
            writer.WriteStringValue("node_name", NodeName);
            writer.WriteStringValue("remark", Remark);
            writer.WriteIntValue("remote_port", RemotePort);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("tunnel_token", TunnelToken);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
