// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RoriaSharp.Api.User.Oauth.Authorization.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RoriaSharp.Api.User.Oauth.Authorization
{
    /// <summary>
    /// Builds and executes requests for operations under \user\oauth\authorization
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthorizationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the RoriaSharp.Api.user.oauth.authorization.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::RoriaSharp.Api.User.Oauth.Authorization.Item.WithClient_ItemRequestBuilder"/></returns>
        public global::RoriaSharp.Api.User.Oauth.Authorization.Item.WithClient_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("client_id", position);
                return new global::RoriaSharp.Api.User.Oauth.Authorization.Item.WithClient_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.Oauth.Authorization.AuthorizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthorizationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/oauth/authorization", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.Oauth.Authorization.AuthorizationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthorizationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/oauth/authorization", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
