// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RoriaSharp.Api.Admin.Tunnel.Item.Traffic
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TrafficGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The connections property</summary>
        public int? Connections { get; set; }
        /// <summary>The custom_domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomDomain { get; set; }
#nullable restore
#else
        public string CustomDomain { get; set; }
#endif
        /// <summary>The node_id property</summary>
        public int? NodeId { get; set; }
        /// <summary>The node_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeName { get; set; }
#nullable restore
#else
        public string NodeName { get; set; }
#endif
        /// <summary>The remark property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remark { get; set; }
#nullable restore
#else
        public string Remark { get; set; }
#endif
        /// <summary>The remote_port property</summary>
        public int? RemotePort { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The total_traffic property</summary>
        public int? TotalTraffic { get; set; }
        /// <summary>The traffic_in property</summary>
        public int? TrafficIn { get; set; }
        /// <summary>The traffic_out property</summary>
        public int? TrafficOut { get; set; }
        /// <summary>The tunnel_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TunnelName { get; set; }
#nullable restore
#else
        public string TunnelName { get; set; }
#endif
        /// <summary>The tunnel_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TunnelType { get; set; }
#nullable restore
#else
        public string TunnelType { get; set; }
#endif
        /// <summary>The updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.Admin.Tunnel.Item.Traffic.TrafficGetResponse_data"/> and sets the default values.
        /// </summary>
        public TrafficGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RoriaSharp.Api.Admin.Tunnel.Item.Traffic.TrafficGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RoriaSharp.Api.Admin.Tunnel.Item.Traffic.TrafficGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RoriaSharp.Api.Admin.Tunnel.Item.Traffic.TrafficGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "connections", n => { Connections = n.GetIntValue(); } },
                { "custom_domain", n => { CustomDomain = n.GetStringValue(); } },
                { "node_id", n => { NodeId = n.GetIntValue(); } },
                { "node_name", n => { NodeName = n.GetStringValue(); } },
                { "remark", n => { Remark = n.GetStringValue(); } },
                { "remote_port", n => { RemotePort = n.GetIntValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "total_traffic", n => { TotalTraffic = n.GetIntValue(); } },
                { "traffic_in", n => { TrafficIn = n.GetIntValue(); } },
                { "traffic_out", n => { TrafficOut = n.GetIntValue(); } },
                { "tunnel_name", n => { TunnelName = n.GetStringValue(); } },
                { "tunnel_type", n => { TunnelType = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("connections", Connections);
            writer.WriteStringValue("custom_domain", CustomDomain);
            writer.WriteIntValue("node_id", NodeId);
            writer.WriteStringValue("node_name", NodeName);
            writer.WriteStringValue("remark", Remark);
            writer.WriteIntValue("remote_port", RemotePort);
            writer.WriteStringValue("status", Status);
            writer.WriteIntValue("total_traffic", TotalTraffic);
            writer.WriteIntValue("traffic_in", TrafficIn);
            writer.WriteIntValue("traffic_out", TrafficOut);
            writer.WriteStringValue("tunnel_name", TunnelName);
            writer.WriteStringValue("tunnel_type", TunnelType);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
