// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using RoriaSharp.Api.Admin;
using RoriaSharp.Api.Client;
using RoriaSharp.Api.Home;
using RoriaSharp.Api.Oauth2;
using RoriaSharp.Api.Tunnel;
using RoriaSharp.Api.User;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RoriaSharp.Api
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The admin property</summary>
        public global::RoriaSharp.Api.Admin.AdminRequestBuilder Admin
        {
            get => new global::RoriaSharp.Api.Admin.AdminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The client property</summary>
        public global::RoriaSharp.Api.Client.ClientRequestBuilder Client
        {
            get => new global::RoriaSharp.Api.Client.ClientRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The home property</summary>
        public global::RoriaSharp.Api.Home.HomeRequestBuilder Home
        {
            get => new global::RoriaSharp.Api.Home.HomeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth2 property</summary>
        public global::RoriaSharp.Api.Oauth2.Oauth2RequestBuilder Oauth2
        {
            get => new global::RoriaSharp.Api.Oauth2.Oauth2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tunnel property</summary>
        public global::RoriaSharp.Api.Tunnel.TunnelRequestBuilder Tunnel
        {
            get => new global::RoriaSharp.Api.Tunnel.TunnelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::RoriaSharp.Api.User.UserRequestBuilder User
        {
            get => new global::RoriaSharp.Api.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
