// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RoriaSharp.Api.User.Traffic.Tunnel.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithTunnel_GetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The connections property</summary>
        public int? Connections { get; set; }
        /// <summary>The last_update property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdate { get; set; }
#nullable restore
#else
        public string LastUpdate { get; set; }
#endif
        /// <summary>The node_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeId { get; set; }
#nullable restore
#else
        public string NodeId { get; set; }
#endif
        /// <summary>The total_traffic property</summary>
        public long? TotalTraffic { get; set; }
        /// <summary>The traffic_in property</summary>
        public long? TrafficIn { get; set; }
        /// <summary>The traffic_out property</summary>
        public long? TrafficOut { get; set; }
        /// <summary>The tunnel_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TunnelName { get; set; }
#nullable restore
#else
        public string TunnelName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RoriaSharp.Api.User.Traffic.Tunnel.Item.WithTunnel_GetResponse_data"/> and sets the default values.
        /// </summary>
        public WithTunnel_GetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RoriaSharp.Api.User.Traffic.Tunnel.Item.WithTunnel_GetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RoriaSharp.Api.User.Traffic.Tunnel.Item.WithTunnel_GetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::RoriaSharp.Api.User.Traffic.Tunnel.Item.WithTunnel_GetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "connections", n => { Connections = n.GetIntValue(); } },
                { "last_update", n => { LastUpdate = n.GetStringValue(); } },
                { "node_id", n => { NodeId = n.GetStringValue(); } },
                { "total_traffic", n => { TotalTraffic = n.GetLongValue(); } },
                { "traffic_in", n => { TrafficIn = n.GetLongValue(); } },
                { "traffic_out", n => { TrafficOut = n.GetLongValue(); } },
                { "tunnel_name", n => { TunnelName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("connections", Connections);
            writer.WriteStringValue("last_update", LastUpdate);
            writer.WriteStringValue("node_id", NodeId);
            writer.WriteLongValue("total_traffic", TotalTraffic);
            writer.WriteLongValue("traffic_in", TrafficIn);
            writer.WriteLongValue("traffic_out", TrafficOut);
            writer.WriteStringValue("tunnel_name", TunnelName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
